input_devices:
  orba: "Artiphon Orba"

output_devices:
  emc: "Elektron Model:Cycles"

pipelines:
  - name: "Distribute Example"
    transforms:
      # Distributes the notes on/off between the given channels
      # This can be useful for instance to play chords on
      - !Distribute
        between: [0, 1, 2]
      # Output the notes!
      # First note played will go to channel 1 on the model cycles
      # second will go to channel 2... and so on
      - !Output emc
