input_devices:
  # Change me!
  orba: "Artiphon Orba"

output_devices:
  # Change me!
  midi: "Midi Through"

pipelines:
  - name: "WASM Example"
    transforms:
      # Only use NoteOn, NoteOff and Controller
      - type: Filter
        event_types: [NoteOn, NoteOff, Controller]
      # Process the notes with the following wasm module
      - type: Wasm
        path: ./build/release.wasm
      # Output the notes!
      - type: Output
        output_device: midi
